server:
  servlet:
    context-path: /api/v1
  port: 8094

firebase:
  type: ${TYPE}
  project_id: ${PROJECT_ID}
  private_key_id: ${PRIVATE_KEY_ID}
  private_key: ${PRIVATE_KEY}
  client_email: ${CLIENT_EMAIL}
  client_id: ${CLIENT_ID}
  auth_uri: https://accounts.google.com/o/oauth2/auth
  token_uri: https://oauth2.googleapis.com/token
  auth_provider_x509_cert_url: https://www.googleapis.com/oauth2/v1/certs
  client_x509_cert_url: ${CLIENT_X509_CERT_URL}
  universe_domain: googleapis.com

spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: ms-hamburguerpage
